### ISSUE TITLE
大哥，能问一下 lite 精简了什么吗？

### ISSUE THREAD

**Issue by Hunlongyu** [GengGode/qt-5.15.2-lite-release-static#1]
我下载 https://github.com/BeamMW/qt5.15.2-static-Windows 静态库，编译后9MB。
下载老哥你的，编译后 7.8MB
想知道精简了哪些模块吗？

**Comment by GengGode** [comment]
只保留了core gui widget，其他任何模块都没有编译，QFont好像会有问题
